
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jan 26 20:53:11 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 48;
  public static final int CONST = 11;
  public static final int EQUAL_COMPARE = 3;
  public static final int NOT_EQUAL = 32;
  public static final int CONTINUE = 43;
  public static final int LPAREN = 7;
  public static final int GREATER = 33;
  public static final int SEMI = 10;
  public static final int LESS = 35;
  public static final int MINUS = 28;
  public static final int RPAREN = 8;
  public static final int AND = 49;
  public static final int RECORD = 17;
  public static final int OR = 38;
  public static final int COMMA = 9;
  public static final int ORD = 2;
  public static final int CLASS = 15;
  public static final int INC = 19;
  public static final int DIV = 30;
  public static final int LESS_EQUAL = 36;
  public static final int PLUS = 27;
  public static final int IF = 37;
  public static final int DOT = 21;
  public static final int BOOLEAN = 47;
  public static final int EOF = 0;
  public static final int RETURN = 44;
  public static final int EQUAL = 12;
  public static final int GREATER_EQUAL = 34;
  public static final int NEW = 26;
  public static final int error = 1;
  public static final int MUL = 29;
  public static final int NUMBER = 45;
  public static final int MOD = 31;
  public static final int IDENT = 46;
  public static final int BREAK = 42;
  public static final int VOID = 18;
  public static final int COLON = 22;
  public static final int ELSE = 39;
  public static final int LBRACE = 5;
  public static final int LSQUARE = 13;
  public static final int READ = 23;
  public static final int GOTO = 25;
  public static final int WHILE = 41;
  public static final int RSQUARE = 14;
  public static final int RBRACE = 6;
  public static final int EXTENDS = 16;
  public static final int PROG = 4;
  public static final int DEC = 20;
  public static final int DO = 40;
  public static final int PRINT = 24;
}

